trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*
      - refs/tags/*
  paths:
    exclude:
      - '**/*.md'
      - '.appveyor.yml'
      - '.codecov.yml'
      - 'GitVersion.yml'
      - 'GitReleaseManager.yaml'
      - .vscode/*
      - .git*
      - .editorconfig
      - .nuke
      - LICENSE

pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.12.0
      endpoint: github

variables:
  - name: CONFIGURATION
    value: Mock
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: '$(Agent.BuildDirectory)/c'
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: TARGET_PLATFORM
    value: iPhoneSimulator
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
  - name: CodeCovToken
    value: ''
  - group: rsg-bot
  # Fixes the github package repo warnings on restore
  - name: EmitAssetsLogMessages
    value: false
  - name: HideWarningsAndErrors
    value: true

jobs:
  - template: jobs/gitversion.yml@rsg

  - job: Build
    variables:
      - group: rsg-bot
    strategy:
      matrix:
        macOS:
          BuildName: 'macOS'
          ImageName: 'macOS-latest'
    pool:
      vmImage: $(ImageName)
    steps:
      - template: support/mono.yml@rsg
      - template: support/install-dotnet.yml@rsg
        parameters:
          DotNetSdk:
            - '2.x'
            - '3.x'
      - template: support/gitversion-hack.yml@rsg

      - task: DotNetCoreCLI@2
        displayName: 'dotnet tool restore'
        inputs:
          command: custom
          custom: tool
          arguments: 'restore'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: restore
          feedsToUse: config
          nugetConfigPath: NuGet.config
          verbosityRestore: Minimal

      - bash: ./build.sh --configuration '$(Configuration)' --target-platform $(Target_Platform) --artifacts '$(Artifacts)' --verbosity '$(Verbosity)'
        displayName: '⚙ Build'

      - template: support/publish-artifacts.yml@rsg
        parameters:
          Artifacts: $(Artifacts)
          Configuration: $(Configuration)
          Coverage: $(Coverage)
          Postfix: ' - $(BuildName)'
          PublishVSTest: true
